version: "2"
run:
  concurrency: 4
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - depguard
    - gochecknoglobals
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - varnamelen
    - noinlineerr
    - wsl # replaced by wsl_v5
    - err113 # maybe remove later
    - exhaustruct # annoying
  settings:
    gocritic:
      disabled-checks:
        - commentFormatting
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
